DPSMate.localization.name = "DPSMate"

DPSMate.localization.parser = {}
DPSMate.localization.parser.youhit = "You hit "
DPSMate.localization.parser.youcrit = "You crit "
DPSMate.localization.parser.hits = " hits "
DPSMate.localization.parser.crits = " crits "
DPSMate.localization.parser.Dfor = " for "
DPSMate.localization.parser.youmiss = "You miss "
DPSMate.localization.parser.parries = "parries"
DPSMate.localization.parser.dodges = "dodges"
DPSMate.localization.parser.your = "Your "
DPSMate.localization.parser.isparriedby = " is parried by "
DPSMate.localization.parser.wasresistedby = " was resisted by "
DPSMate.localization.parser.wasdodgedby = " was dodged by "
DPSMate.localization.parser.missed = " missed "